apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-sample
spec:
  parallelism: 2
  cleanup: post
  script:
    configMap:
      name: load-test
      file: test.js
  arguments: -o experimental-prometheus-rw